add endpoint for validating a token
SmartCity-2022/Service-MainHub pull request #7
Opened 2022-05-18 14:19 UTC by FinnAmini

- Endpoint für das Validieren eines Tokens hinzugefügt

2022-05-18 17:25 UTC, HerrVergesslich approved these changes

2022-05-18 17:31 UTC, HerrVergesslich requested changes
Pls Discord

2022-05-22 21:43 UTC, HerrVergesslich approved these changes

2022-05-22 21:43 UTC, HerrVergesslich commented on frontend/src/components/Login.js
> +            document.cookie = `accessToken=${res.accessToken}`
Naja, diese Cookie Namen

Sowas wie "SmartCityToken" oder so wäre cooler :D

2022-05-22 21:49 UTC, JustinKuehnel commented on frontend/src/components/Login.js
> +            document.cookie = `accessToken=${res.accessToken}`
Antrag abgelehnt ( ͡• ͜ʖ ͡• )

2022-05-22 23:17 UTC, merged